# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapKitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapKitTest
pod 'SnapKit'
pod 'Then'

  target 'SnapKitTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapKitTestUITests' do
    # Pods for testing
  end

end
